apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resources.fullname" . }}
  labels:
    {{- include "resources.labels" . | nindent 4 }}
type: Opaque
stringData:
  php-database-settings: |-
    <?php
    defined('BASEPATH') OR exit('No direct script access allowed');
    $active_group = 'default';
    $query_builder = TRUE;
    $db['default'] = array(
      'dsn' => '',
      'hostname' => '{{ .Values.app.db.host }}',
      'username' => '{{ .Values.app.db.user }}',
      'password' => '{{ .Values.app.db.password }}',
      'database' => '{{ .Values.app.db.name }}',
      'dbdriver' => 'mysqli',
      'dbprefix' => '',
      'pconnect' => FALSE,
      'db_debug' => (ENVIRONMENT !== 'production'),
      'cache_on' => FALSE,
      'cachedir' => '',
      'char_set' => 'utf8',
      'dbcollat' => 'utf8_general_ci',
      'swap_pre' => '',
      'encrypt' => FALSE,
      'compress' => FALSE,
      'stricton' => FALSE,
      'failover' => array(),
      'save_queries' => TRUE
    );
