---
{{- if .Values.ingress.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "resources.webFullname" . }}
  labels:
    {{- include "resources.webLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.webPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "resources.webSelectorLabels" . | nindent 4 }}
{{- end }}
