apiVersion: v1
kind: Secret
metadata:
  name: {{ include "holborn-wordpress.fullname" . }}
  labels:
    {{- include "holborn-wordpress.labels" . | nindent 4 }}
type: Opaque
stringData:
  dbUsername: {{ .Values.wordpress.db.user }}
  dbPassword: {{ .Values.wordpress.db.pass }}
  dbName:     {{ .Values.wordpress.db.name }}
  nonceKey:       {{ .Values.wordpress.secure.nonceKey }}
  authSalt:       {{ .Values.wordpress.secure.authSalt }}
  secureAuthSalt: {{ .Values.wordpress.secure.secureAuthSalt }}
  loggedInSalt:   {{ .Values.wordpress.secure.loggedInSalt }}
  nonceSalt:      {{ .Values.wordpress.secure.nonceSalt }}
data:
  authKey:        {{ default "false" .Values.wordpress.secure.authKey       | b64enc }}
  secureAuthKey:  {{ default "false" .Values.wordpress.secure.secureAuthKey | b64enc }}
  loggedInKey:    {{ default "false" .Values.wordpress.secure.loggedInKey   | b64enc }}
