apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "holborn-wordpress.webFullname" . }}
  labels:
    {{- include "holborn-wordpress.webLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "holborn-wordpress.webSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/nginxConfig: {{ include (print $.Template.BasePath "/web-configmap.yaml") . | sha256sum | trunc 63 }}
      labels:
        {{- include "holborn-wordpress.webSelectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "holborn-wordpress.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.webRepo }}:{{ .Values.image.webTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: redirect
              containerPort: 88
              protocol: TCP
          livenessProbe:
            #periodSeconds:  20
            #failureThreshold: 100
            httpGet:
              path: /_healthz/index.html
              port: http
          readinessProbe:
            #periodSeconds:  20
            #failureThreshold: 100
            httpGet:
              path: /_healthz/index.html
              port: http
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
          volumeMounts:
          - mountPath:  /etc/nginx/nginx.conf
            name:       nginx-config
            subPath:    nginx-conf
            readOnly:   true
          - mountPath:  /etc/nginx/conf.d/default.conf
            name:       nginx-config
            subPath:    default-conf
            readOnly:   true
          - mountPath:  /etc/nginx/fastcgi.conf
            name:       nginx-config
            subPath:    fastcgi-conf
            readOnly:   true
          - mountPath:  /var/www/html
            name:       webroot
          - mountPath:  /var/www/html/docs
            subPath:    docs
            name:       nfs-hdiver
          - mountPath:  /var/www/html/members-private
            subPath:    members-private
            name:       nfs-hdiver
          - mountPath:  /var/www/html/wp-includes
            subPath:    wp-includes
            name:       nfs-hdiver
          - mountPath:  /var/www/html/wp-content
            subPath:    wp-content
            name:       nfs-hdiver
          - mountPath:  /var/www/html/wp-admin
            subPath:    wp-admin-static
            name:       nfs-hdiver
          - mountPath:  /var/www/html/{{ .Values.wordpress.google.siteVerification }}
            subPath:    gsv
            name:       nginx-config
            readOnly:   true
        {{- if .Values.wordpress.resource.enabled }}
        {{- toYaml .Values.wordpress.resource.mounts | nindent 10 }}
        {{- end }}
      volumes:
        - name: webroot
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: {{ include "holborn-wordpress.webFullname" . }}
        # Additional mounts
        {{- with .Values.wordpress.mounts.additionalVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        # Resource mounts
        {{- with .Values.wordpress.resource.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
